global:

  client:
    database:
      port: 5432
      name: clientdb
      username: "user"
      password: "password"

  app:
    baseUrl: http://api-service:8080
    imagePullPolicy: Always
    replicaCount: 1
    port: 8080

  backend:
    database:
      replicaCount: 1
      port: 5432
      name: testdb
      username: "user"
      password: "password"
    pgbouncer:
      host: "postgresql://pgbouncer-service:6432/testdb"
      hostName: "pgbouncer-service"
      port: 6432