apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
spec:
  selector:
    app: backend-database
  ports:
    - port: {{ .Values.global.backend.pgbouncer.port }}
      targetPort: {{ .Values.global.backend.pgbouncer.port }}
      protocol: TCP
