apiVersion: v1
kind: ConfigMap
metadata:
  name: client-sql-config
data:
  init-query.sql: |
    CREATE TABLE runs (
      "id" SERIAL PRIMARY KEY,
      "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
      "clientVersion" VARCHAR NOT NULL,
      "appName" VARCHAR NOT NULL,
      "appVersion" VARCHAR NOT NULL,
      "appConfig" JSONB NOT NULL,
      "cpusPerNode" INTEGER NOT NULL,
      "scenarioName" VARCHAR NOT NULL,
      "initialRequestsPerSecond" INTEGER NOT NULL,
      "maxConnections" INTEGER NOT NULL,
      "workerCount" INTEGER NOT NULL,
      "cpusUsed" INTEGER NOT NULL,
      "trialDurationSeconds" INTEGER NOT NULL,
      "timeoutSeconds" INTEGER NOT NULL,
      "minWaitSeconds" INTEGER NOT NULL,
      "totalRunDurationSeconds" INTEGER NOT NULL,
      "bestTrialID" INTEGER REFERENCES trials(id)
    );

    CREATE INDEX idx_results_client_version ON results(clientVersion);
    CREATE INDEX idx_results_client_action ON results(clientAction);
    CREATE INDEX idx_results_app_name ON results(appName);
    CREATE INDEX idx_results_app_version ON results(appVersion);
    CREATE INDEX idx_results_app_config ON results USING GIN (appConfig);
    CREATE INDEX idx_results_scenario_name ON results(scenarioName);

    CREATE TABLE trials (
      "id" SERIAL PRIMARY KEY,
      "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
      "runID" INTEGER REFERENCES runs(id) NOT NULL,
      "requestsPerSecond" DOUBLE PRECISION NOT NULL,
      "percentSuccesfullyCompleting" DOUBLE PRECISION NOT NULL,
      "successfulCompletesPerSecond" DOUBLE PRECISION NOT NULL,
      "totalRequests" INTEGER NOT NULL,
      "meanLatency" VARCHAR NOT NULL,
      "maxLatency" VARCHAR NOT NULL,
      "latency50thPercentile" VARCHAR NOT NULL,
      "latency95thPercentile" VARCHAR NOT NULL,
      "latency99thPercentile" VARCHAR NOT NULL,
      "histogram" JSONB NOT NULL,
      "statusCodes" JSONB NOT NULL,
      "errorMessages" VARCHAR,
      "availablePorts" INTEGER NOT NULL,
      "fileDescriptors" INTEGER NOT NULL,
      "remainingPortsActive" INTEGER NOT NULL,
      "remainingPortsWaiting" INTEGER NOT NULL,
      "remainingFDsInUse" INTEGER NOT NULL
    );
