apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        kubernetes.io/hostname: client

      # Uncomment this to completely re-install the database.
#      initContainers:
#        - name: clear-data
#          image: busybox
#          command: [ 'sh', '-c', 'rm -rdf /var/lib/postgresql/data/*' ]
#          volumeMounts:
#            - name: postgres-data
#              mountPath: /var/lib/postgresql/data

      containers:

        - name: client
          image: {{ .Values.global.app.dockerImagePrefix }}/bench:latest
          imagePullPolicy: {{ .Values.global.app.imagePullPolicy }}
          env:
            - name: CLIENT_DATABASE_URL
              value: "{{ .Values.global.client.database.host }}"
            - name: CLIENT_DATABASE_USERNAME
              value: "{{ .Values.global.client.database.username }}"
            - name: CLIENT_DATABASE_PASSWORD
              value: "{{ .Values.global.client.database.password }}"
            - name: BASE_APP_URL
              value: "{{ .Values.global.app.baseUrl }}"
            - name: BACKEND_DATABASE_URL
              value: "{{ .Values.global.backend.pgbouncer.host }}"
            - name: BACKEND_DATABASE_USERNAME
              value: "{{ .Values.global.backend.database.username }}"
            - name: BACKEND_DATABASE_PASSWORD
              value: "{{ .Values.global.backend.database.password }}"

        - name: client-database
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: {{ .Values.global.client.database.name }}
            - name: POSTGRES_USER
              value: {{ .Values.global.client.database.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.client.database.password }}
          ports:
            - containerPort: {{ .Values.global.client.database.port }}
          volumeMounts:
            - name: client-sql-config
              mountPath: /docker-entrypoint-initdb.d/
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: client-postgres-volume-claim

        - name: client-sql-config
          configMap:
            name: client-sql-config

