apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      nodeSelector:
        kubernetes.io/hostname: client
      containers:
        - name: client
          image: {{ .Values.global.app.dockerImagePrefix }}/bench:latest
          imagePullPolicy: {{ .Values.global.app.imagePullPolicy }}
          env:
            - name: BASE_APP_URL
              value: "{{ .Values.global.app.baseUrl }}"
            - name: DATABASE_URL
              value: "{{ .Values.global.backend.pgbouncer.host }}"
            - name: DATABASE_USERNAME
              value: "{{ .Values.global.backend.database.username }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.global.backend.database.password }}"

