{
 "title": "Server Metrics - CPU/Memory/Disk",
 "description": "Custom - Dashboard to view multiple servers",
 "tags": [ "IB" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1m,2m,3m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"system\",instance=~'$node'}[$interval]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"user\",instance=~'$node'}[$interval]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"nice\",instance=~'$node'}[$interval]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"iowait\",instance=~'$node'}[$interval]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"steal\",instance=~'$node'}[$interval]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"idle\",instance=~'$node'}[$interval]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"irq\",instance=~'$node'}[$interval]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"softirq\",instance=~'$node'}[$interval]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",instance=~'$node'}[$interval])) or sum(irate(node_cpu{mode=\"guest\",instance=~'$node'}[$interval]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=~\"$node\"}[$interval]) or irate(node_context_switches{instance=~\"$node\"}[$interval])",
     "legendFormat": "context switches"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{instance=~'$node'} - node_memory_MemFree_bytes{instance=~'$node'} - node_memory_Buffers_bytes{instance=~'$node'} - node_memory_Cached_bytes{instance=~'$node'} - node_memory_SwapCached_bytes{instance=~'$node'} - node_memory_Slab_bytes{instance=~'$node'} - node_memory_PageTables_bytes{instance=~'$node'} - node_memory_VmallocUsed_bytes{instance=~'$node'} ) or ( node_memory_MemTotal{instance=~'$node'} - node_memory_MemFree{instance=~'$node'} - node_memory_Buffers{instance=~'$node'} - node_memory_Cached{instance=~'$node'} - node_memory_SwapCached{instance=~'$node'} - node_memory_Slab{instance=~'$node'} - node_memory_PageTables{instance=~'$node'} - node_memory_VmallocUsed{instance=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$node'} or node_memory_Buffers{instance=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node'} or node_memory_Cached{instance=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node'} or node_memory_MemFree{instance=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~'$node'} or node_memory_Slab{instance=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$node'} or node_memory_SwapCached{instance=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~'$node'} or node_memory_PageTables{instance=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{instance=~'$node'} or node_memory_VmallocUsed{instance=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'}) or (node_memory_SwapTotal{instance=~'$node'} - node_memory_SwapFree{instance=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{instance=~'$node'} or node_memory_Committed_AS{instance=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{instance=~'$node'} or node_memory_Mapped{instance=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~'$node'} or node_memory_Active{instance=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{instance=~'$node'} or node_memory_Inactive{instance=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{instance=~'$node',device !~'tmpfs',device!~'by-uuid'}) or 100.0 - 100 * (node_filesystem_avail{instance=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{instance=~'$node',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}