environments:
  default:
    values:
      # required to templatize files that helmfile loads
      - charts/global-values.yaml

---

helmDefaults:
  timeout: 30

releases:
  # backend database

  - name: backend-database
    chart: charts/backend-database
    values:
      - charts/global-values.yaml

  # client group

  - name: client
    chart: charts/client
    labels:
      clientGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml

  - name: prometheus
    chart: prometheus-community/prometheus
    values:
      - charts/values-prometheus.yaml
    labels:
      clientGroup: "true"

  - name: grafana
    chart: grafana/grafana
    values:
      - charts/values-grafana.yaml
    labels:
      clientGroup: "true"
    hooks:
      - events: ['presync']
        command: 'kubectl'
        args:
          - create
          - configmap
          - node-metrics-dashboard
          - --from-file=charts/client/dashboards/node-metrics-dashboard.json
      - events: ['postuninstall']
        command: 'kubectl'
        args:
          - delete
          - configmap
          - node-metrics-dashboard

  # application group

  - name: jooby-nomvc-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-nomvc-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/values-secret.yaml
      - charts/global-values.yaml
      - env-vars/generic-env-vars.yaml.gotmpl

  - name: jooby-r2dbc-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-r2dbc-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/values-secret.yaml
      - charts/global-values.yaml
      - env-vars/generic-env-vars.yaml.gotmpl

  - name: jooby-vertx-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-vertx-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/values-secret.yaml
      - charts/global-values.yaml
      - env-vars/generic-env-vars.yaml.gotmpl

  - name: spring-async-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "spring-async-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/values-secret.yaml
      - charts/global-values.yaml

  - name: spring-jdbc-kernel-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-kernel-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/values-secret.yaml
      - charts/global-values.yaml
      - spring:
          threads:
            virtual:
              enabled: "false"
      - env-vars/spring-jdbc-env-vars.yaml.gotmpl

  - name: spring-jdbc-virtual-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-virtual-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/values-secret.yaml
      - charts/global-values.yaml
      - spring:
          threads:
            virtual:
              enabled: "true"
      - env-vars/spring-jdbc-env-vars.yaml.gotmpl

  - name: spring-webflux-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "spring-webflux-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - charts/global-values.yaml
      - charts/values-secret.yaml
      - env-vars/spring-r2dbc-env-vars.yaml.gotmpl