environments:
  default:
    values:
      # required to templatize files that helmfile loads
      - charts/global-values.yaml

---

helmDefaults:
  timeout: 30

releases:
  # backend database

  - name: backend-database
    chart: charts/backend-database
    values:
      - charts/global-values.yaml

  # client group

  - name: client
    chart: charts/client
    labels:
      clientGroup: "true"
    values:
      - charts/global-values.yaml

  # application group

  - name: jooby-jdbc-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-jdbc-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - appVersion: "0.1.0"
      - charts/global-values.yaml
      - env-vars/generic-env-vars.yaml.gotmpl

  - name: jooby-r2dbc-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-r2dbc-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - appVersion: "0.1.0"
      - charts/global-values.yaml
      - env-vars/generic-env-vars.yaml.gotmpl

  - name: jooby-vertx-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "jooby-vertx-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - appVersion: "0.1.0"
      - charts/global-values.yaml
      - env-vars/generic-env-vars.yaml.gotmpl

  - name: spring-async-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "spring-async-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - appVersion: "0.1.0"
      - charts/global-values.yaml

  - name: spring-jdbc-kernel-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-kernel-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - appVersion: "0.1.0"
      - charts/global-values.yaml
      - spring:
          threads:
            virtual:
              enabled: "false"
      - env-vars/spring-jdbc-env-vars.yaml.gotmpl

  - name: spring-jdbc-virtual-app
    chart: charts/spring-jdbc-app
    installed: {{ .Values | getOrNil "spring-jdbc-virtual-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - appVersion: "0.1.0"
      - charts/global-values.yaml
      - spring:
          threads:
            virtual:
              enabled: "true"
      - env-vars/spring-jdbc-env-vars.yaml.gotmpl

  - name: spring-webflux-app
    chart: charts/generic-app
    installed: {{ .Values | getOrNil "spring-webflux-app_installed" | default false }}
    labels:
      appGroup: "true"
    values:
      - appVersion: "0.1.0"
      - charts/global-values.yaml
      - env-vars/spring-r2dbc-env-vars.yaml.gotmpl